### ISSUE TITLE
Can I use other civitai models?

### ISSUE THREAD

**Issue by upright2003** [ayush-thakur02/stable-diffusion-xl#2]
For example:
https://civitai.com/models/118406/counterfeitxl

I think your git project is great, very helpful when other webui is disabled by colab,
Can I customize and download other models?
You can also output output.jpg by specifying the output directory? And seed.jpg?
Thank you!

**Comment by ayush-thakur02** [comment]
Sure, you can use other Civitai Models. I'll need to configure the pipeline for them. Additionally, I'll create a dedicated directory to store all these images, making it easier for you to download them as a zip file.

_If you find this project helpful, please consider sharing and giving it a star! :)_

**Comment by upright2003** [comment]
Thank you and look forward to your updates~
